In [1]:
import pandas as pd 
import numpy as np

In [2]:
t_train=pd.read_csv(r"C:\Users\abhis\Desktop\Python\Data\train.csv")

In [3]:
t_test=pd.read_csv(r"C:\Users\abhis\Desktop\Python\Data\test.csv")

In [4]:
t_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
t_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
t_test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
t_test['Survived']=np.nan

In [8]:
t_test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [9]:
t_train['data']='train'
t_test['data']='test'
t_all=pd.concat([t_train,t_test],axis=0)

C:\Users\abhis\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
t_all.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket   data  
0       3    male      1       0.0         A/5 21171  train  
1       1  female      1       1.0          PC 17599  train  
2       3  female      0       1.0  STON/O2. 3101282  train  
3       1  female      1       1.0            113803  train  
4       3    male      0       0.0            373450  train

In [11]:
t_all.dtypes

Age            float64
Cabin           object
Embarked        object
Fare           float64
Name            object
Parch            int64
PassengerId      int64
Pclass           int64
Sex             object
SibSp            int64
Survived       float64
Ticket          object
data            object
dtype: object

In [12]:
t_all.drop(['Name','Ticket','Cabin',],axis=1,inplace=True)

In [13]:
t_all.head()

Age Embarked     Fare  Parch  PassengerId  Pclass     Sex  SibSp  \
0  22.0        S   7.2500      0            1       3    male      1   
1  38.0        C  71.2833      0            2       1  female      1   
2  26.0        S   7.9250      0            3       3  female      0   
3  35.0        S  53.1000      0            4       1  female      1   
4  35.0        S   8.0500      0            5       3    male      0   

   Survived   data  
0       0.0  train  
1       1.0  train  
2       1.0  train  
3       1.0  train  
4       0.0  train

In [14]:
cat_cols=t_all.select_dtypes(['object']).columns

In [15]:
cat_cols

Index(['Embarked', 'Sex', 'data'], dtype='object')

In [16]:
cat_cols=cat_cols[:-1]

In [17]:
cat_cols

Index(['Embarked', 'Sex'], dtype='object')

In [18]:
for col in cat_cols:
    freqs=t_all[col].value_counts()
    k=freqs.index[freqs>20][:-1]
    for cat in k:
        name=col+'_'+cat
        t_all[name]=(t_all[col]==cat).astype(int)
    del t_all[col]
    print(col)

Embarked
Sex


In [19]:
t_all.head()
t_all.dtypes

Age            float64
Fare           float64
Parch            int64
PassengerId      int64
Pclass           int64
SibSp            int64
Survived       float64
data            object
Embarked_S       int32
Embarked_C       int32
Sex_male         int32
dtype: object

In [20]:
t_all.shape

(1309, 11)

In [21]:
t_all.isnull().sum()

Age            263
Fare             1
Parch            0
PassengerId      0
Pclass           0
SibSp            0
Survived       418
data             0
Embarked_S       0
Embarked_C       0
Sex_male         0
dtype: int64

In [22]:
for col in t_all.columns:
    if (col not in ['Survived','data'])& (t_all[col].isnull().sum()>0):
        t_all.loc[t_all[col].isnull(),col]=t_all.loc[t_all['data']=='train',col].mean()

In [23]:
t_all.isnull().sum()

Age              0
Fare             0
Parch            0
PassengerId      0
Pclass           0
SibSp            0
Survived       418
data             0
Embarked_S       0
Embarked_C       0
Sex_male         0
dtype: int64

In [24]:
t_train=t_all[t_all['data']=='train']
del t_train['data']
t_test=t_all[t_all['data']=='test']
t_test.drop(['Survived','data'],axis=1,inplace=True)

C:\Users\abhis\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import Ridge,Lasso
from sklearn.model_selection import GridSearchCV

In [26]:
params={'class_weight':['balanced',None],
        'penalty':['l1','l2'],
        'C':np.linspace(0.01,1000,10)}

In [27]:
model=LogisticRegression(fit_intercept=True)

In [28]:
grid_search=GridSearchCV(model,param_grid=params,cv=5,scoring="roc_auc",verbose=4)

In [29]:
x_train=t_train.drop('Survived',axis=1)
y_train=t_train['Survived']

In [30]:
y_train=t_train['Survived']

In [31]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV] C=0.01, class_weight=balanced, penalty=l1 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l1, score=0.5641633728590251, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l1 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l1, score=0.7337285902503294, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l1 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l1, score=0.6890374331550801, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l1 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l1, score=0.7474598930481283, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l1 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l1, score=0.7481111710739342, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l2 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l2, score=0.7409749670

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.1s remaining:    0.0s


[CV]  C=0.01, class_weight=balanced, penalty=l2, score=0.8208168642951251, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l2 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l2, score=0.8118983957219251, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l2 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l2, score=0.8212566844919788, total=   0.0s
[CV] C=0.01, class_weight=balanced, penalty=l2 .......................
[CV]  C=0.01, class_weight=balanced, penalty=l2, score=0.8679168915272532, total=   0.0s
[CV] C=0.01, class_weight=None, penalty=l1 ...........................
[CV]  C=0.01, class_weight=None, penalty=l1, score=0.5666666666666667, total=   0.0s
[CV] C=0.01, class_weight=None, penalty=l1 ...........................
[CV]  C=0.01, class_weight=None, penalty=l1, score=0.7266139657444006, total=   0.0s
[CV] C=0.01, class_weight=None, penalty=l1 ...........................
[CV]  C=0.01, class_weight=None, penalty=l1, sco

[CV]  C=333.34, class_weight=balanced, penalty=l1, score=0.8328063241106719, total=   0.0s
[CV] C=333.34, class_weight=balanced, penalty=l1 .....................
[CV]  C=333.34, class_weight=balanced, penalty=l1, score=0.852139037433155, total=   0.0s
[CV] C=333.34, class_weight=balanced, penalty=l1 .....................
[CV]  C=333.34, class_weight=balanced, penalty=l1, score=0.8342245989304813, total=   0.0s
[CV] C=333.34, class_weight=balanced, penalty=l1 .....................
[CV]  C=333.34, class_weight=balanced, penalty=l1, score=0.8723691311386941, total=   0.0s
[CV] C=333.34, class_weight=balanced, penalty=l2 .....................
[CV]  C=333.34, class_weight=balanced, penalty=l2, score=0.8462450592885375, total=   0.0s
[CV] C=333.34, class_weight=balanced, penalty=l2 .....................
[CV]  C=333.34, class_weight=balanced, penalty=l2, score=0.8326745718050066, total=   0.0s
[CV] C=333.34, class_weight=balanced, penalty=l2 .....................
[CV]  C=333.34, class_weight=

[CV]  C=555.56, class_weight=None, penalty=l1, score=0.8716945493793847, total=   0.0s
[CV] C=555.56, class_weight=None, penalty=l2 .........................
[CV]  C=555.56, class_weight=None, penalty=l2, score=0.8480895915678525, total=   0.0s
[CV] C=555.56, class_weight=None, penalty=l2 .........................
[CV]  C=555.56, class_weight=None, penalty=l2, score=0.8333333333333334, total=   0.0s
[CV] C=555.56, class_weight=None, penalty=l2 .........................
[CV]  C=555.56, class_weight=None, penalty=l2, score=0.8525401069518717, total=   0.0s
[CV] C=555.56, class_weight=None, penalty=l2 .........................
[CV]  C=555.56, class_weight=None, penalty=l2, score=0.837433155080214, total=   0.0s
[CV] C=555.56, class_weight=None, penalty=l2 .........................
[CV]  C=555.56, class_weight=None, penalty=l2, score=0.8715596330275228, total=   0.0s
[CV] C=666.67, class_weight=balanced, penalty=l1 .....................
[CV]  C=666.67, class_weight=balanced, penalty=l1, sc

[CV]  C=888.89, class_weight=None, penalty=l1, score=0.8482213438735178, total=   0.0s
[CV] C=888.89, class_weight=None, penalty=l1 .........................
[CV]  C=888.89, class_weight=None, penalty=l1, score=0.833201581027668, total=   0.0s
[CV] C=888.89, class_weight=None, penalty=l1 .........................
[CV]  C=888.89, class_weight=None, penalty=l1, score=0.852673796791444, total=   0.0s
[CV] C=888.89, class_weight=None, penalty=l1 .........................
[CV]  C=888.89, class_weight=None, penalty=l1, score=0.8381016042780748, total=   0.0s
[CV] C=888.89, class_weight=None, penalty=l1 .........................
[CV]  C=888.89, class_weight=None, penalty=l1, score=0.871424716675661, total=   0.0s
[CV] C=888.89, class_weight=None, penalty=l2 .........................
[CV]  C=888.89, class_weight=None, penalty=l2, score=0.8488801054018444, total=   0.0s
[CV] C=888.89, class_weight=None, penalty=l2 .........................
[CV]  C=888.89, class_weight=None, penalty=l2, score=0.

[Parallel(n_jobs=1)]: Done 200 out of 200 | elapsed:    5.3s finished


GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'class_weight': ['balanced', None], 'penalty': ['l1', 'l2'], 'C': array([1.0000e-02, 1.1112e+02, 2.2223e+02, 3.3334e+02, 4.4445e+02,
       5.5556e+02, 6.6667e+02, 7.7778e+02, 8.8889e+02, 1.0000e+03])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=4)

In [32]:
grid_search.best_estimator_

LogisticRegression(C=111.12, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [33]:
logr=grid_search.best_estimator_

In [34]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [35]:
report(grid_search.cv_results_,5)

Model with rank: 1
Mean validation score: 0.849 (std: 0.013)
Parameters: {'C': 111.12, 'class_weight': None, 'penalty': 'l2'}

Model with rank: 2
Mean validation score: 0.849 (std: 0.013)
Parameters: {'C': 333.34, 'class_weight': None, 'penalty': 'l1'}

Model with rank: 3
Mean validation score: 0.849 (std: 0.013)
Parameters: {'C': 444.45, 'class_weight': None, 'penalty': 'l1'}

Model with rank: 4
Mean validation score: 0.849 (std: 0.013)
Parameters: {'C': 444.45, 'class_weight': None, 'penalty': 'l2'}

Model with rank: 5
Mean validation score: 0.849 (std: 0.013)
Parameters: {'C': 777.78, 'class_weight': None, 'penalty': 'l1'}



In [36]:
logr.fit(x_train,y_train)

LogisticRegression(C=111.12, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [37]:
cutoffs=np.linspace(0.01,0.99,99)

cutoffs

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99])

In [38]:
train_score=logr.predict_proba(x_train)[:,1]

real=y_train

train_score

array([0.08542873, 0.91905002, 0.62263717, 0.88937467, 0.0720895 ,
       0.11893708, 0.26043777, 0.09128404, 0.56902081, 0.90018137,
       0.72322721, 0.81079107, 0.12232905, 0.03048691, 0.72487241,
       0.61549092, 0.09493617, 0.22147132, 0.5022633 , 0.68606623,
       0.19211619, 0.19402742, 0.78182326, 0.48401669, 0.54395653,
       0.32892094, 0.12746661, 0.40249333, 0.66922609, 0.08734237,
       0.46966339, 0.948356  , 0.66925798, 0.06458043, 0.53452832,
       0.29048281, 0.12758158, 0.11847979, 0.54919342, 0.74714392,
       0.41182626, 0.77788148, 0.12780282, 0.92152188, 0.75447604,
       0.08749847, 0.09084452, 0.66959811, 0.07374092, 0.62659769,
       0.05899868, 0.11857593, 0.88266668, 0.76621468, 0.24658504,
       0.46834521, 0.85647044, 0.13311376, 0.87367018, 0.03474248,
       0.16513851, 0.93665606, 0.28044599, 0.07931433, 0.57023146,
       0.08962913, 0.8139712 , 0.12721744, 0.35169972, 0.05541177,
       0.20646733, 0.30752917, 0.31248478, 0.11111072, 0.08855

In [39]:
real

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ... 
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [40]:
train_score>0.2

array([False,  True,  True,  True, False, False,  True, False,  True,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
       False, False,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
       False,  True, False,  True, False,  True, False,  True,  True,
        True, False, False, False, False, False,  True,  True, False,
       False,  True,  True,  True,  True, False, False,  True, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False,  True, False,  True, False, False, False,  True, False,
       False,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True, False, False,  True,  True,  True, False,
       False, False,

In [41]:
KS_all=[]
A_all=[]
for cutoff in cutoffs:
    
    predicted=(train_score>cutoff).astype(int)

    TP=((predicted==1) & (real==1)).sum()
    TN=((predicted==0) & (real==0)).sum()
    FP=((predicted==1) & (real==0)).sum()
    FN=((predicted==0) & (real==1)).sum()
    
    P=TP+FN
    N=TN+FP
    Accuracy=(TP+TN)/(TP+TN+FP+FN)
    KS=(TP/P)-(FP/N)
    
    A_all.append(Accuracy)
    KS_all.append(KS)

In [42]:
A_all

[0.388327721661055,
 0.3894500561167228,
 0.39281705948372614,
 0.40404040404040403,
 0.4163860830527497,
 0.43658810325476993,
 0.45791245791245794,
 0.47474747474747475,
 0.5061728395061729,
 0.5544332210998878,
 0.569023569023569,
 0.6094276094276094,
 0.6520763187429854,
 0.6823793490460157,
 0.6947250280583613,
 0.6992143658810326,
 0.7037037037037037,
 0.7070707070707071,
 0.7104377104377104,
 0.712682379349046,
 0.7205387205387206,
 0.7250280583613917,
 0.7384960718294051,
 0.745230078563412,
 0.7519640852974186,
 0.7598204264870931,
 0.7665544332210998,
 0.7676767676767676,
 0.7732884399551067,
 0.7732884399551067,
 0.7755331088664422,
 0.7811447811447811,
 0.7822671156004489,
 0.7822671156004489,
 0.7856341189674523,
 0.7867564534231201,
 0.7867564534231201,
 0.7878787878787878,
 0.7867564534231201,
 0.7890011223344556,
 0.7901234567901234,
 0.7901234567901234,
 0.7878787878787878,
 0.7890011223344556,
 0.7912457912457912,
 0.792368125701459,
 0.7957351290684624,
 0.7957351290

In [43]:
KS_all

[0.007285974499089298,
 0.00910746812386154,
 0.014571948998178486,
 0.032786885245901676,
 0.05282331511839711,
 0.08340523439746905,
 0.11580864730131335,
 0.1398236027226536,
 0.18200556034895976,
 0.2537148883136804,
 0.27077940753523155,
 0.3341482120602052,
 0.3978525548844789,
 0.44262295081967207,
 0.46045441472533793,
 0.4633304572907679,
 0.46951394880644237,
 0.47167098073051483,
 0.47603297862141697,
 0.4774709999041319,
 0.4902214552775381,
 0.49640494679321256,
 0.5160579043236506,
 0.5269868660722845,
 0.5368133448375036,
 0.548461317227495,
 0.5593902789761289,
 0.5601092896174864,
 0.569216757741348,
 0.5670117917745183,
 0.5662448470904036,
 0.5720448662640206,
 0.5705589109385486,
 0.5661489790048893,
 0.5694084939123766,
 0.5668200556034896,
 0.56461508963666,
 0.5664365832614323,
 0.5624101236698302,
 0.5660531109193749,
 0.5667721215607324,
 0.5645671555939027,
 0.5587192023775285,
 0.5594382130188861,
 0.5608762343016009,
 0.5626977279263733,
 0.5659572428338606,

In [44]:
max(KS_all)

0.5760233918128654

In [45]:
max(A_all)

0.8181818181818182

In [65]:
mycutoff=cutoffs[A_all==max(A_all)][0]
mycutoff

0.6

In [66]:
logr.intercept_

array([5.08152158])

In [67]:
list(zip(x_train.columns,logr.coef_[0]))

[('Age', -0.038909996897488294),
 ('Fare', 0.002057291951272069),
 ('Parch', -0.09560241337591975),
 ('PassengerId', 0.00010246799898525618),
 ('Pclass', -1.080141182190641),
 ('SibSp', -0.31952026938881695),
 ('Embarked_S', -0.34529275972068685),
 ('Embarked_C', 0.07937338388121207),
 ('Sex_male', -2.706055861001125)]

In [68]:
test_score=logr.predict_proba(t_test)[:,1]
pd.DataFrame(test_score).to_csv("mysubmission.csv",index=False)

PermissionError: [Errno 13] Permission denied: 'mysubmission.csv'

In [69]:
test_score

array([0.10911195, 0.36665827, 0.11049449, 0.10421071, 0.58461628,
       0.16190819, 0.68600544, 0.1970062 , 0.79037466, 0.07416568,
       0.09473253, 0.33318608, 0.93723375, 0.05981972, 0.84896269,
       0.86957664, 0.26342972, 0.18321927, 0.55854646, 0.56899056,
       0.295417  , 0.1742262 , 0.93458388, 0.66418911, 0.90381829,
       0.03384684, 0.96612796, 0.17479365, 0.38030352, 0.08008121,
       0.09559434, 0.17601151, 0.45960312, 0.49312893, 0.52537112,
       0.19852178, 0.61108237, 0.68819826, 0.11223014, 0.10393781,
       0.09316618, 0.48616927, 0.0633458 , 0.82218166, 0.85688398,
       0.11197901, 0.44545904, 0.12916196, 0.88073703, 0.50824273,
       0.47917055, 0.34786027, 0.76979448, 0.88642591, 0.324745  ,
       0.07793177, 0.07880344, 0.11204504, 0.07209823, 0.96501496,
       0.14705015, 0.22273409, 0.14222494, 0.75004037, 0.66292669,
       0.82658553, 0.77818011, 0.33331224, 0.58068044, 0.7788707 ,
       0.73531846, 0.12870699, 0.6183377 , 0.60388385, 0.96278

In [80]:
test_score=(test_score>mycutoff).astype(int)

In [81]:
t_list=list(zip(t_test['PassengerId'],test_score))
type(t_list)
test_classes=pd.DataFrame(t_list)
print(test_classes)

        0  1
0     892  0
1     893  0
2     894  0
3     895  0
4     896  0
..    ... ..
413  1305  0
414  1306  1
415  1307  0
416  1308  0
417  1309  0

[418 rows x 2 columns]


In [82]:
pd.DataFrame(test_classes).to_csv("mysubmission.csv",index=False)